#!/usr/bin/env python3
"""
Smart Traffic Light System - Log Analysis Tool
Analyzes CSV logs generated by the firmware simulation.
"""

import csv
import sys
import os
from collections import Counter
from datetime import datetime


def analyze_log(log_file):
    """Analyze the simulation log CSV file."""
    
    if not os.path.exists(log_file):
        print(f"Error: Log file '{log_file}' not found")
        return
    
    print(f"\n{'='*60}")
    print(f"LOG ANALYSIS: {log_file}")
    print(f"{'='*60}\n")
    
    events = []
    emergency_events = []
    fault_events = []
    
    with open(log_file, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            events.append(row)
            if row['system_state'] == 'EMERGENCY':
                emergency_events.append(row)
            elif row['system_state'] == 'FAULT':
                fault_events.append(row)
    
    total_events = len(events)
    emergency_count = len(emergency_events)
    fault_count = len(fault_events)
    normal_events = total_events - emergency_count - fault_count
    
    print(f"Total events logged: {total_events}")
    print(f"Normal traffic events: {normal_events}")
    print(f"Emergency events: {emergency_count}")
    print(f"Fault events: {fault_count}")
    
    if emergency_events:
        print(f"\n--- Emergency Events ---")
        approaches = Counter(e.get('north_light', '') for e in emergency_events)
        for approach, count in approaches.most_common():
            print(f"  {approach}: {count}")
        
        response_times = []
        for e in emergency_events:
            west_light = e.get('west_light', '')
            if west_light and west_light.isdigit():
                response_times.append(int(west_light))
        if response_times:
            print(f"  Average response time: {sum(response_times)/len(response_times):.1f} ms")
            print(f"  Min response time: {min(response_times)} ms")
            print(f"  Max response time: {max(response_times)} ms")
    
    if fault_events:
        print(f"\n--- Fault Events ---")
        fault_types = Counter(e['fault_status'] for e in fault_events)
        for fault, count in fault_types.most_common():
            print(f"  {fault}: {count}")
    
    # Traffic state distribution
    print(f"\n--- Traffic State Distribution ---")
    state_counts = Counter(e['system_state'] for e in events)
    for state, count in state_counts.most_common():
        print(f"  {state}: {count} ({count/total_events*100:.1f}%)")
    
    # Light state distribution
    print(f"\n--- Traffic Light States ---")
    for direction in ['north_light', 'south_light', 'east_light', 'west_light']:
        light_counts = Counter(e[direction] for e in events)
        print(f"  {direction}:")
        for light, count in light_counts.most_common():
            print(f"    {light}: {count}")
    
    # RFID events
    rfid_events = [e for e in events if e['rfid_event'] != 'none']
    print(f"\n--- RFID Events ---")
    print(f"  Total RFID events: {len(rfid_events)}")
    if rfid_events:
        rfid_tags = Counter(e['rfid_event'] for e in rfid_events)
        for tag, count in rfid_tags.most_common():
            print(f"  {tag}: {count}")
    
    # Fault status analysis
    print(f"\n--- Fault Status ---")
    fault_counts = Counter(e['fault_status'] for e in events)
    for fault, count in fault_counts.most_common():
        if fault != '0x00000000':
            print(f"  {fault}: {count}")
    
    # Time range
    timestamps = [int(e['timestamp_ms']) for e in events if e['timestamp_ms'].isdigit()]
    if timestamps:
        print(f"\n--- Time Range ---")
        print(f"  Start: {min(timestamps)} ms")
        print(f"  End: {max(timestamps)} ms")
        print(f"  Duration: {max(timestamps) - min(timestamps)} ms")
    
    print(f"\n{'='*60}")


def main():
    if len(sys.argv) < 2:
        log_file = "logs/simulation_log.csv"
    else:
        log_file = sys.argv[1]
    
    analyze_log(log_file)


if __name__ == "__main__":
    main()